blank_issues_enabled: false
contact_links:
  - name: Privacy / Consent (read before posting)
    url: https://github.com/yks0000/calc-issues/issues/new/choose
    about: Do not include personal information in public issues.
